### ISSUE TITLE
Feature Checklist

### ISSUE THREAD

**Issue by yordis** [straw-hat-team/straw_hat_iam#35]
- [ ] Username|email/password authentication
- [ ] Token authentication (exchange a valid credential for a token)
- [ ] OAuth through all major providers (Facebook, Google, Twitter, etc)
- [ ] The ability to convert an OAuth code from Facebook/Google/Twitter into an API token
- [ ] Magic links: Passwordless
- [ ] Two-factor authentication (SMS, One-Time-Passwords)
- [ ] Password Policies
- [ ] Standard Protocols: OpenID Connect, OAuth 2.0 and SAML 2.0
- [ ] Single-Sign On. Login once to multiple applications
- [ ] LDAP and Active Directory. Connect to existing user directories
- [ ] Identity Brokering. OpenID Connect or SAML 2.0 IdPs

There are basically two functions that I think an IAM service would need:

- *Authenticate*: Give me a valid credential, and I'll give you a user identity. This credential can be:
 - A username/password pair
 - A token previously issued by IAM
 - A foreign OAuth code from Facebook, Google, Twitter
 - Two-factor auth requires two authenticate calls: 1) submit original credential and 2) submit second factor

- *Tokenize*: Give me a valid credential, and I'll trade you a token that represents the user attached to that credential. This token can then be passed to *Authenticate* to validate and identify the user later on.
 - You can use this for mobile API authentication: tokenize the user's credentials and save the token on the mobile device
 - You can also use it for passwordless: tokenize the user's email address/phone number, and send that token to them by email/sms

### Useful links
- http://www.keycloak.org/
- https://github.com/pwdless/cierge
- https://www.pingidentity.com/en.html
- https://auth0.com/

![accessmanagement](https://user-images.githubusercontent.com/4237280/36170690-e9fd45c4-10b4-11e8-99d9-fa0aa72a57f7.gif)

**Comment by zacck** [comment]
@yordis  as we discussed please see my sentiments on the bottom right section 
the bottom right sections would make more sense if you called it

enumerables
or  collections
see it has an `identity store` i.e it can keep all your ids
metadata synch  is likely what are doing when checking that a policy is applied for every transaction
i.e if I make a call then the policies change then my next call should be affected
virtual directory is  just a filtered list of anything
